---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.33.0
      hooks:
          - id: markdownlint
            args: [--config, markdownlint_config.json, -fix]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/sirwart/ripsecrets
      rev: v0.1.5
      hooks:
          - id: ripsecrets

    - repo: https://github.com/nrbeach/requirements_checker
      rev: v0.1.1
      hooks:
          - id: requirements_checker
            args: [--files, 'requirements.txt,requirements-dev.txt']
