# Generated by Django 4.2.1 on 2023-05-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
