# Generated by Django 4.2.1 on 2023-05-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='interfaces',
            field=models.ManyToManyField(blank=True, to='web.interface'),
        ),
    ]
