# Generated by Django 4.2.1 on 2023-05-13 22:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_component_interfaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="voltage_operating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
